In [2]:
print("Hello, Data Cleaning!")

Hello, Data Cleaning!

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("../data/titanic.csv")

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.shape

(891, 12)

In [7]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [9]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [10]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage.sort_values(ascending=False)

Cabin          77.104377
Age            19.865320
Embarked        0.224467
PassengerId     0.000000
Name            0.000000
Pclass          0.000000
Survived        0.000000
Sex             0.000000
Parch           0.000000
SibSp           0.000000
Fare            0.000000
Ticket          0.000000
dtype: float64

In [11]:
df["Cabin"].head(20)

0      NaN
1      C85
2      NaN
3     C123
4      NaN
5      NaN
6      E46
7      NaN
8      NaN
9      NaN
10      G6
11    C103
12     NaN
13     NaN
14     NaN
15     NaN
16     NaN
17     NaN
18     NaN
19     NaN
Name: Cabin, dtype: str

In [12]:
df = df.drop(columns=["Cabin"])

In [13]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='str')

In [16]:
df = df.drop(columns=["Cabin"])

KeyError: "['Cabin'] not found in axis"

In [17]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='str')

In [18]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

In [19]:
df = pd.read_csv("../data/titanic.csv")

In [20]:
df["Cabin"] = df["Cabin"].fillna("Unknown")

In [21]:
df["Cabin"].isnull().sum()

np.int64(0)

In [22]:
df["Age"].isnull().sum()

np.int64(177)

In [23]:
df["Age"].median()

np.float64(28.0)

In [24]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [25]:
df["Age"].isnull().sum()

np.int64(0)

In [26]:
df["Embarked"].isnull().sum()

np.int64(2)

In [27]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [28]:
df["Embarked"].mode()[0]

'S'

In [29]:
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [30]:
df["Embarked"].isnull().sum()

np.int64(0)

In [31]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [34]:
type(df["Sex"].dtype)

pandas.StringDtype

In [35]:
df["Sex"] = df["Sex"].astype("category")
df["Cabin"] = df["Cabin"].astype("category")
df["Embarked"] = df["Embarked"].astype("category")

In [36]:
print(df["Sex"].dtype)
print(df["Cabin"].dtype)
print(df["Embarked"].dtype)

category
category
category

In [37]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [38]:
df.shape

(891, 12)

In [39]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Unknown,S

In [40]:
df.to_csv("../data/titanic_cleaned.csv", index=False)

In [41]:
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

## Data Cleaning Assumptions

The following assumptions were made during the data-cleaning process:

### 1. Cabin

Missing values in the `Cabin` column were replaced with `"Unknown"`.

The value `"Unknown"` represents unavailable cabin information and does not mean that the passenger did not have a cabin.

### 2. Age

Missing values in the `Age` column were replaced with the median age of the dataset.

The median was selected because Age is a numerical variable and the median is less affected by extreme values than the mean.

### 3. Embarked

Missing values in the `Embarked` column were replaced with the most frequently occurring value (mode).

Only a small number of observations were missing, so using the most common category was considered reasonable.

### 4. Duplicate Records

The dataset was checked for duplicate rows. No duplicate rows were found, so no records were removed.

### 5. Data Types

The `Sex`, `Cabin`, and `Embarked` columns were converted to the `category` data type because they represent categorical information.

### 6. Data Preservation

No rows were removed during the cleaning process. Missing information was handled through appropriate replacement strategies wherever possible.

## Cleaning Summary

| Column | Problem | Action Taken |
|---|---|---|
| Cabin | Missing values | Replaced with `"Unknown"` |
| Age | Missing values | Replaced with median |
| Embarked | Missing values | Replaced with mode |
| All columns | Duplicate check | No duplicates found |
| Sex, Cabin, Embarked | Categorical data | Converted to `category` |

## Final Validation

The cleaned dataset was validated by checking:

- Missing values
- Duplicate rows
- Dataset dimensions
- Data types

The final dataset contains no missing values and no duplicate rows.
The cleaned dataset was saved as `titanic_cleaned.csv`.

In [42]:
print("Missing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nDataset shape:")
print(df.shape)

print("\nData types:")
print(df.dtypes)

Missing values:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

Duplicate rows:
0

Dataset shape:
(891, 12)

Data types:
PassengerId       int64
Survived          int64
Pclass            int64
Name                str
Sex            category
Age             float64
SibSp             int64
Parch             int64
Ticket              str
Fare            float64
Cabin          category
Embarked       category
dtype: object

# Conclusion

The Titanic dataset was successfully cleaned using Python and Pandas.

The cleaning process included:

1. Inspecting the dataset structure.
2. Identifying missing values.
3. Replacing missing Cabin values with `"Unknown"`.
4. Replacing missing Age values with the median age.
5. Replacing missing Embarked values with the mode.
6. Checking for duplicate records.
7. Handling categorical data types.
8. Performing final validation.
9. Exporting the cleaned dataset.

The original dataset was preserved, and the cleaned version was saved separately as `titanic_cleaned.csv`.

The assumptions behind the cleaning decisions were documented to make the process transparent and reproducible.